version: 2
updates:
  - directory: /
    open-pull-requests-limit: 5
    rebase-strategy: auto
    package-ecosystem: gomod
    schedule:
      interval: weekly
      time: "00:00"
      day: saturday
      timezone: Asia/Tokyo
    groups:
      all-go-dependencies:
        patterns:
          - "*"

  - directory: /
    open-pull-requests-limit: 5
    rebase-strategy: auto
    package-ecosystem: github-actions
    schedule:
      interval: weekly
      time: "00:00"
      day: saturday
      timezone: Asia/Tokyo
